### ISSUE TITLE
Typos In Part 1

### ISSUE THREAD

**Issue by ytmimi** [calebsander/git-internals#1]
Hey Caleb,

Great article, and I'm looking forward to reading the rest of the parts as you release them!!  I noticed two typos that I wanted to point out.

The first sentence reads: __"This is the first of several posts exploring the ``how`` git works under the hood"__.
I think you meant to get rid of the "how" so that its reads: __"This is the first of several posts exploring how git works under the hood"__.

In section __Implementing a git command__ in the 3rd paragraph after the code block you write: __"we can merge these two sorted slices to process all entries in both ``tries``"__. Should ``tries`` be ``trees``?

Again, I'm very much looking forward to rest of the articles and I hope it helps that I pointed these two things out!

**Comment by calebsander** [comment]
Yup, good catch.
